### ISSUE TITLE
spring-graphql example

### ISSUE THREAD

**Issue by nilshartmann** [spring-petclinic/spring-petclinic-graphql#36]
Hi,

on the branch [spring-graphql](https://github.com/spring-petclinic/spring-petclinic-graphql/tree/spring-graphql) I started implementing an example based on the [recently announced](https://spring.io/blog/2021/07/06/hello-spring-graphql) new [spring-graphql](https://github.com/spring-projects/spring-graphql) project.

I wonder if we:

1. should replace the existing example (that uses the outdated graphql-java-tools lib, that is now [graphql-java-kickstart](https://github.com/graphql-java-kickstart) with the `spring-graphql`-based one (merge `spring-graphql`-branch to `master`)
2. _or_ if we should create a new GitHub repo with the new example `spring-graphql`-example.

Myself, I'm unsure, but tend to option 1, as the current example is outdated anyway (and we can create an own branch for that example to make it still accessible for everyone) and `spring-graphql` might become the "offcial" GraphQL solution for spring anyway in the near future.

What do you think?

Best,
Nils

**Comment by arey** [comment]
Hi Nils,

I saw this announcement and like you I believe that the new `spring-graphql` project will become the solution to adopt for GraphQL endpoint in the Spring ecosystem.
Thus yes I may replace the `master` branch with your recent work.

Antoine

**Comment by nilshartmann** [comment]
Hi Antoine,

thanks for your feedback!

Before merging I'd like to add some tests, to make the example more feature complete. 

Nils
