### ISSUE TITLE
npm install -> errors

### ISSUE THREAD

**Issue by oaj** [spring-petclinic/spring-petclinic-graphql#42]
xxx@pop-os:~/projects/tests/spring-petclinic-graphql/frontend$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-scripts@4.0.1
npm ERR! Found: typescript@4.1.3
npm ERR! node_modules/typescript
npm ERR!   typescript@"^4.1.3" from the root project
npm ERR!   peer typescript@">=2.7" from ts-node@9.1.1
npm ERR!   node_modules/ts-node
npm ERR!     ts-node@"^9" from @endemolshinegroup/cosmiconfig-typescript-loader@3.0.2
npm ERR!     node_modules/@endemolshinegroup/cosmiconfig-typescript-loader
npm ERR!       @endemolshinegroup/cosmiconfig-typescript-loader@"3.0.2" from graphql-config@3.2.0
npm ERR!       node_modules/graphql-config
npm ERR!         graphql-config@"^3.2.0" from @graphql-codegen/cli@1.20.0
npm ERR!         node_modules/@graphql-codegen/cli
npm ERR!     peerOptional ts-node@">=9.0.0" from jest-config@26.6.3
npm ERR!     node_modules/jest-config
npm ERR!       jest-config@"^26.6.3" from @jest/core@26.6.3
npm ERR!       node_modules/@jest/core
npm ERR!         @jest/core@"^26.6.0" from jest@26.6.0
npm ERR!         node_modules/jest
npm ERR!         1 more (jest-cli)
npm ERR!       3 more (jest-runner, jest-runtime, jest-cli)
npm ERR!   1 more (tsutils)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@"^3.2.1" from react-scripts@4.0.1
npm ERR! node_modules/react-scripts
npm ERR!   react-scripts@"4.0.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: typescript@3.9.10
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@"^3.2.1" from react-scripts@4.0.1
npm ERR!   node_modules/react-scripts
npm ERR!     react-scripts@"4.0.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/xxxj/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxx/.npm/_logs/2022-06-18T20_13_33_959Z-debug-0.log

**Comment by nilshartmann** [comment]
I will close this, as the frontend has received a major upgrade including almost all libraries.
