### ISSUE TITLE
Login page error

### ISSUE THREAD

**Issue by shyaml** [spring-petclinic/spring-petclinic-graphql#45]
I could not compile and run the front-end application. The LoginPage.tsx would not compile  giving 
} catch (err) {
			console.error("LOGIN FAILED ================ >>>>>>>>>>>>>>>>> ", err);
			setLoginRequestState({ error: err.message });
		}

at line 54,34

I do get login screen after npm start  but application crashed

**Comment by nilshartmann** [comment]
I will close this because the frontend has gotten a major upgrade recently, including an upgrade of many libraries. So you should try the newest version.
