### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jpeddicord** [spring-petclinic/spring-petclinic-graphql#9]
Hi! I'm having trouble finding out what license this code is released under. In [one other project](https://github.com/spring-petclinic/spring-petclinic-microservices) in this org I saw that it was Apache 2.0. Does this have that license too? If so, could a license file be added?

Thanks!

**Comment by arey** [comment]
Like the other projects, the `spring-petclinic-graphql` project is released with the APACHE 2.0 licence. I've just added the licence file. See commit https://github.com/spring-petclinic/spring-petclinic-graphql/commit/e07a8359a92985212ffb9d340c20cf8a25c4671e
